### ISSUE TITLE
Map Filter - Intersect relation with Extent not with center point

### ISSUE THREAD

**Issue by vladymir30** [Esri/geoportal-server-catalog#104]
Hello team!,

I'm just trying to figure out how to find metadata using the map filter, but when I try to use the option "Intersects" just appear metadata that the centroid is touched by the map extent, and I have a lot of metadata that should appear if the map filter with intersects works with the metadata extent... theres something that i'm not doing well or some configuration???

![image](https://user-images.githubusercontent.com/15157740/32017917-cfba186e-b98d-11e7-8b27-04889a38399f.png)

Best regards,

Vladymir

**Comment by umacgillivray** [comment]
It's querying based on the center point of the metadata rather than the extent of the metadata. We had some performance issues with large datasets, that's why we made this change. We are going to make this configurable, and allow the user to change in a coming release. For now you could modify:

https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/webapp/app/search/SpatialFilter.js

Comment out these lines:

        qry = {"geo_bounding_box": {
          "envelope_cen_pt" : {
            "top_left" : {
              "lat" : env.ymax,
              "lon" : env.xmin
            },
            "bottom_right" : {
              "lat" : env.ymin,
              "lon" : env.xmax
            }
          }
        }};

**Comment by vladymir30** [comment]
Thank's I made the changes, and work fine!
