### ISSUE TITLE
End-of-life for Elasticsearch 5.x

### ISSUE THREAD

**Issue by rmbradley** [Esri/geoportal-server-catalog#181]
We currently use Elasticsearch (ES) 5.4.0 in our sandbox Geoportal 2.6.  We originally configured Geoportal 2.5 with ES 5.4.0 when it was released and continue to use 5.4.0.  The Geoportal 2.6 installation links to 2.5 documents - looks like nothing has changed from a Geoportal aspect.
However, on Elastic's site https://www.elastic.co/support/eol, it is stated that 5.4.0 EOL is 2018-11-04.  We understand that Geoportal 2.6 is compatible with ES 5.x.  In addition the latest ES is 5.6.x with an EOL of 2019-03-11 and will be maintained until ES 7.0 is released.

What Elasticsearch version is recommended for planning a production release of Geoportal 2.6 ( or later) no less than a year from now?  Any advice will help.

Thanks,

Rick

**Comment by valentinedwv** [comment]
Thoughts on handling,
"Rejecting mapping update to [metadata_v1] as the final mapping would have more than 1 type: [clob, item, blob]"

Multiple mapping types are not supported in indices created in 6.0
https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking-changes-6.0.html

Think we have to add source filtering and excludes to a new model

**Comment by valentinedwv** [comment]
Reindexing 5 to 6 may have issues:
During reindexing, the useSeparateXML flag gets set to true. This means that the GPT now looks for the XML in a field, and since this was an original, there is no xml field, it is in the clob.

1) do not reindex on a production machine, for now.
1.1) need a special case for upgrading from a v5 index to a new v6 index that does not 

I can't see where the xml is going. it is no field called "sys_xml_clob" in the stored JSON
