### ISSUE TITLE
CSW client. Ignore endpoints in GetCapabilities

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#204]
misconfigured CSW servers often do not have the correct endpoint, especially when proxied.
Can we have an always use the provided URL or ignore endpoints in GetCapabilities.?

http://search.geothermaldata.org/csw?service=CSW&version=2.02&request=GetCapabilities

```
<ows:Operation name="DescribeRecord">
<ows:DCP>
<ows:HTTP>
<ows:Get xlink:type="simple" xlink:href="http://127.0.0.1/csw"/>
<ows:Post xlink:type="simple" xlink:href="http://127.0.0.1/csw"/>
</ows:HTTP>
</ows:DCP>
<ows:Parameter name="schemaLanguage">
<ows:Value>http://www.w3.org/XML/Schema</ows:Value>
<ows:Value>http://www.w3.org/TR/xmlschema-1/</ows:Value>
</ows:Parameter>
<ows:Parameter name="outputFormat">
<ows:Value>application/xml</ows:Value>
<ows:Value>application/json</ows:Value>
</ows:Parameter>
<ows:Parameter name="typeName">
<ows:Value>csw:Record</ows:Value>
<ows:Value>gmd:MD_Metadata</ows:Value>
</ows:Parameter>
</ows:Operation>
```

**Comment by mhogeweg** [comment]
This is an age-old dilemma. We have seen many occurrences of this with various OGC services (and ArcGIS Servers). Ideally you would not work around a basic configuration, but instead provide feedback to the owners to correct their configuration. Why? Because even though your geoportal may be able to handle it, consuming it in webmaps, desktop GIS and other unforeseen clients will still fail.
