### ISSUE TITLE
Display METADATA in other languages

### ISSUE THREAD

**Issue by sagatchua** [Esri/geoportal-server-catalog#251]
Hi. We'd like to deploy our metadata catalogue on Geoportal Server, but we need our metadata (title and description) to be displayed according to the user localization. Each metadata is available in several languages in a single XML, and we'd like it (title and description) to be displayed in german for a german user and in french for a french user. 

Here is an example of an xml which contains metadata in several languages : https://www.geocat.ch/geonetwork/srv/api/records/781e7f5a-a99f-4d91-95fb-8428ff9c95e0/formatters/xml  

So far, we could only display our geoportal interface in other languages according to the user localization, but not the data itself. Is it possible to do that in a relatively simple way ? 

Thank you very much for your help !

**Comment by mhogeweg** [comment]
hi. one path is to include metadata language as a search facet and then apply that as a filter based on the locale setting of the browser. this would work if you have metadata language separated as individual records that would be filtered by the language facet.

with metadata in multiple languages in the same document, you'd have to update the search results display according to the locale. 

What I would do for this is to update the publishing pipeline to extract individual language titles/descriptions as their own index fields. Then in ItemCard you could display the proper language text by picking the right field from the index.

Take a look at the [ItemCard](https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/webapp/app/search/ItemCard.js) class.

Updating the publishing pipeline would be done by updating (since you have ISO metadata) [EvaluatorFor_ISO.js](https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/resources/metadata/js/EvaluatorFor_ISO.js).

**Comment by mhogeweg** [comment]
One option is to look at configuring elastic with field-specific analyzers as described here: https://www.elastic.co/guide/en/elasticsearch/guide/current/mixed-lang-fields.html.

Curious, how does the metadata get translated into multiple languages? and is the data itself available in those languages as well?

**Comment by sagatchua** [comment]
Thank you for that information. 
The metadata is translated into four languages directly by the Swiss government and it is their policy to provide the data in those languages as well, as you can see at https://map.geo.admin.ch
