### ISSUE TITLE
app/common/ModalDialog

### ISSUE THREAD

**Issue by valentinedwv** [Esri/geoportal-server-catalog#272]
Something in ModalDialog prevents it from rendering a
dijit/form/Select

**Comment by valentinedwv** [comment]
Test:
to app/common/SignIn.js add
```
    ,"dijit/form/Select"
```
To app/common/templates/SiginIn.html insert in the form element:
```
    <div name="select3" value="AK" data-dojo-type="dijit/form/Select">
      <span value="AL"><b>Alabama</b></span>
      <span value="AK"><font color="red">A</font><font color="orange">l</font><font color="yellow">a</font><font color="green">s</font><font color="blue">k</font><font color="purple">a</font></span>
      <span value="AZ"><i>Arizona</i></span>
      <span value="AR"><span class="ark">Arkansas</span></span>
      <span value="CA"><span style="font-size:25%">C</span><span style="font-size:50%">a</span><span style="font-size:75%">l</span><span style="font-size:90%">i</span><span style="font-size:100%">f</span><span style="font-size:125%">o</span><span style="font-size:133%">r</span><span style="font-size:150%">n</span><span style="font-size:175%">i</span><span style="font-size:200%">a</span></span>
      <span value="NM" disabled="disabled">New<br>  Mexico</span>
    </div>
```

**Comment by pandzel** [comment]
This is happening due to one peculiar design flow in one of the CSS files. Unfortunately, Geoportal team doesn't have a control over that file, so we cannot fix it permanently. 

We can provide some guidance how to mitigate the issue, though. It is all based upon manually setting a 'zIndex' value of a particular elements to the value higher than 1050. Which elements it depends on the Dojo control used on the Dialog box. 

Here is an example how it's been done on the TemporalFilterCallendar dialog:
[https://github.com/Esri/geoportal-server-catalog/pull/245/files#diff-c1f7d887ad20bf176f06bfff4b6ffba9](https://github.com/Esri/geoportal-server-catalog/pull/245/files#diff-c1f7d887ad20bf176f06bfff4b6ffba9)

This dialog has two Calendar widgets. Each calendar widget exposes DropDown-like behavior and needs its zIndex to be adjusted to 1100. Moreover, each such DropDown has another DropDown (months) and that needs to have its zIndex adjusted as well to 1101.
