### ISSUE TITLE
geoportal view other catalog

### ISSUE THREAD

**Issue by alexlau818** [Esri/geoportal-server-catalog#386]
I have added two connection in config.json but still can't see records in viewer catalog 
![config_json](https://user-images.githubusercontent.com/86964065/124694681-5860a200-df14-11eb-84dc-ebe53f931808.jpg)
![geoportal_viewer_catalog](https://user-images.githubusercontent.com/86964065/124694684-5a2a6580-df14-11eb-9cdd-ad57f5d90759.jpg)

Thanks

**Comment by mhogeweg** [comment]
in Geoportal 2.x the search widget submits searches via the search component (as a proxy) to the target catalog. In order to search Geonetwork or CKAN catalogs, you will need to create a profile for the specific API (CSW or for example CKAN's own API) in the search component. Then in the configuration of the search widget you would reference that profile in the configuration of specific catalog.

The place to configure the profile is https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal-search/src/main/resources/gs/target/profiles/profiles.js. You will find a sample that takes for example the envelope, the modified date as information. 

An example configuration of the viewer search widget can be found here: https://github.com/Esri/geoportal-server-catalog/blob/master/geoportal/src/main/webapp/viewer/widgets/GeoportalSearch/example-config.json. Notice the profile attribute for the configured catalogs. This is where you would reference your custom catalog profile.
