### ISSUE TITLE
Error Load Metadata Editor

### ISSUE THREAD

**Issue by jalvarez37** [Esri/geoportal-server-catalog#502]
The metadata editor not loaded on geoportal/#searchpanel

**To Reproduce**
1. Log in like a gptadmin
2. On Admin>Create Metadata
3. Show the Starting Editor...

**Screenshots**
![geoportal_MetadataEditor_Error](https://github.com/Esri/geoportal-server-catalog/assets/37816407/f6e492e2-eb9f-40ac-b651-1a7e9ab3ca0c).

**Desktop (please complete the following information):**
 - OS: Win10 Pro
 - Version: 22H2
 - Browser: Edge 115.0.1901.183, chrome 114.0.5735.248, Brave 1.56.14

**Comment by as0050629** [comment]
Same issue has been raised by Esri India sudipta.kundu@esri.in

**Comment by as0050629** [comment]
This is happening as .js is not recognized as application/javascript. 
To check please run below command
reg query HKCR\.js /v "Content Type"

If key does not exist or it is not application/javascript, below command will update the key
reg add HKCR\.js /v "Content Type" /t REG_SZ /d application/javascript

Now check again 
reg query HKCR\.js /v "Content Type"

It will show as below 
HKEY_CLASSES_ROOT\.js
    Content Type    REG_SZ    application/javascript

Geoportal release 2.7.0 has a filename bug which will still prevent Create Metadata to work. 
It is fixed in 2.7.0 patch 1. So please take https://github.com/Esri/geoportal-server-catalog/tree/2.7.0-patch-1

**Comment by jalvarez37** [comment]
Thanks @as0050629 Ankita.
