### ISSUE TITLE
Active Directory Security configuration

### ISSUE THREAD

**Issue by mgg-eagle** [Esri/geoportal-server-catalog#7]
Hi,

Can you please advise if it possible to configure this version of Geoportal with Windows Active Directory, and if so what are the required changes to make.  If this could be added to the wiki that would be helpful.

Thanks,

Marc

**Comment by MapZombie** [comment]
This would be very helpful.  As the previous version of Geoportal had a very useful wiki https://github.com/Esri/geoportal-server/wiki/Connecting-to-a-User-Directory#ldapAdapter_section_configuration_for_Windows_Active_Directory  could something like this be added or atleast a document that details steps on upgrading from the 1.2.x line.  Thanks.

**Comment by vladymir30** [comment]
Hi,

I was starting a metadata project with this new version of Geoportal 2.0.1 and I have some question about the way to connect with my LDAP:

1. I just install ElasticSearch 2.4, tomcat and geoportal.war (I assumed this new version doesn't need all things configured in v1.2.7 as SQL Server, JDBC, lucene, and gpt.xml because those features are not included in the installer.) so can I say this is a Band New way to deploy and configure Geoportal right?

2. I found some problems connecting with my LDAP, MapZombie share the link to the LDAP Configuration in version 1.2.7 but is focused in explain concepts and configure the gpt.xml (that is not present in v2.01).

So i just used the 2.0.1 installation guide, In conf/app-security  Just activate  <beans:import resource="authentication-ldap.xml"/> 
then in authentication-ldap.xml I Just update the the parameters to use my users in my LDAP and restarted tomcat, when I try to log with the admin user this is the response "Error"   ----> 

2016-11-12 06:09:49,189 INFO [org.springframework.security.oauth2.provider.endpo
int.TokenEndpoint] - Handling error: InvalidGrantException, Bad credentials

This is my configuration>

![image](https://cloud.githubusercontent.com/assets/15157740/20238447/dbeaf774-a8b9-11e6-9b28-883f4b02cc21.png)

<security:ldap-server 
    id="ldapServer"  
    url="ldap://192.168.0.106:389"
    manager-dn="CN=gpt,DC=sigma,DC=pty" 
    manager-password="Qwerty123" />
	
  <security:authentication-manager alias="authenticationManager">
    <security:ldap-authentication-provider 
      server-ref="ldapServer"
      role-prefix="ROLE_"
      user-search-base="CN=Users,DC=sigma,DC=pty" 
	    user-search-filter="(&amp;(objectclass=person)(uid={0}))" 
	    group-search-base="OU=GeoportalRoles,DC=sigma,DC=pty"
	    group-role-attribute="cn" 
	    group-search-filter="(&amp;(objectclass=groupOfUniqueNames)(uniquemember={0}))"
	    user-context-mapper-ref="ldapUserContextMapper">
    </security:ldap-authentication-provider>
  </security:authentication-manager>
  
  <beans:bean id="ldapUserContextMapper" class="com.esri.geoportal.base.security.LdapUserContextMapper">
    <beans:property name="defaultRole" value="USER" />
    <beans:property name="roleMap">
      <beans:map key-type="java.lang.String" value-type="java.lang.String">
        <beans:entry key="ROLE_GPT_ADMINISTRATORS" value="ADMIN,PUBLISHER" />
        <beans:entry key="ROLE_GPT_PUBLISHERS" value="PUBLISHER" />
      </beans:map>
    </beans:property>
  </beans:bean>


/* In my Active directory */
![image](https://cloud.githubusercontent.com/assets/15157740/20238460/4046ca7c-a8ba-11e6-8c26-9bb9fca16125.png)

SecurityPrincipal: gpt
CatalogAdminDN: gptadmin
GeoportalRoles: GPT_ADMINISTRATORS(members: gptadmin)

/*The error*/

![image](https://cloud.githubusercontent.com/assets/15157740/20238489/ceaa2994-a8ba-11e6-8c7c-b0843855735d.png)

2016-11-12 06:09:49,189 INFO [org.springframework.security.oauth2.provider.endpo
int.TokenEndpoint] - Handling error: InvalidGrantException, Bad credentials

Any idea??? I think theres something more i need to configure... :(

Best regards,

Vladymir

**Comment by zguo** [comment]
Yes it should work with Active directory, we just created a wiki (https://github.com/Esri/geoportal-server-catalog/wiki/Security-configuration-LDAP) for configuring geoportal to use LDAP, add some example for Active directory. In the above screenshot, looks like the user-search-filter and group-search-filter need to be updated.

**Comment by DamienB-ESRI** [comment]
@Vladymir - were you able to configure active directory with Geoportal 2.6.x in the end, I have encountered the exact same issue as you, strugging with configuration and the recommendation in the documentations as suggest above.
